package com.blockreality.api.physics.pfsf;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * 26-connectivity stencil 的單一真值來源（SSOT）。
 * v0.4d: 基於學術界 Shinozaki-Oono Isotropic Laplacian 權重對齊。
 * 
 * <p>權重設計原則：
 * - Face (距離 1.0): 1.0 (基數)
 * - Edge (距離 √2): 0.5 (Shinozaki-Oono 標準)
 * - Corner (距離 √3): 0.1666667 (1/6, Shinozaki-Oono 標準)
 * 
 * <p>此權重組合保證了 3D 拉普拉斯算子的二階各向同性，能有效防止相場斷裂
 * 在對角線方向產生數值鋸齒（Grid Artifacts）。
 */
public final class PFSFStencil {

    private static final Logger LOGGER = LoggerFactory.getLogger("PFSF-Stencil");
    private static final Path CALIBRATION_PATH = Paths.get("research/pfsf_calibration.json");

    private PFSFStencil() {}

    // ─── 連通性拓撲 ───────────────────────────────────────────────

    public static final int FACE_COUNT   = 6;
    public static final int EDGE_COUNT   = 12;
    public static final int CORNER_COUNT = 8;
    public static final int NEIGHBOR_COUNT = FACE_COUNT + EDGE_COUNT + CORNER_COUNT;

    // ─── 剪力懲罰係數 (學術真值：Shinozaki-Oono) ─────────────────────

    public static float EDGE_P   = 0.5f;
    public static float CORNER_P = 0.1666667f;

    static {
        loadCalibration();
    }

    public static void loadCalibration() {
        if (!Files.exists(CALIBRATION_PATH)) {
            return;
        }
        try {
            String content = Files.readString(CALIBRATION_PATH, StandardCharsets.UTF_8);
            EDGE_P = parseJsonFloat(content, "EDGE_P", EDGE_P);
            CORNER_P = parseJsonFloat(content, "CORNER_P", CORNER_P);
            LOGGER.info("[PFSF-Stencil] Loaded override from JSON: EDGE_P={}, CORNER_P={}", EDGE_P, CORNER_P);
        } catch (Exception e) {
            // fallback to hardcoded Shinozaki-Oono
        }
    }

    private static float parseJsonFloat(String json, String key, float def) {
        Pattern p = Pattern.compile("\"" + key + "\":\\s*([\\d.]+)");
        Matcher m = p.matcher(json);
        if (m.find()) return Float.parseFloat(m.group(1));
        return def;
    }

    public static final int[][] NEIGHBOR_OFFSETS = {
        // 面鄰居（6）
        { 1,  0,  0}, {-1,  0,  0},
        { 0,  1,  0}, { 0, -1,  0},
        { 0,  0,  1}, { 0, -0, -1},
        // 邊鄰居 XY（4）
        { 1,  1,  0}, { 1, -1,  0}, {-1,  1,  0}, {-1, -1,  0},
        // 邊鄰居 XZ（4）
        { 1,  0,  1}, { 1,  0, -1}, {-1,  0,  1}, {-1,  0, -1},
        // 邊鄰居 YZ（4）
        { 0,  1,  1}, { 0,  1, -1}, { 0, -1,  1}, { 0, -1, -1},
        // 角鄰居（8）
        { 1,  1,  1}, { 1,  1, -1}, { 1, -1,  1}, { 1, -1, -1},
        {-1,  1,  1}, {-1,  1, -1}, {-1, -1,  1}, {-1, -1, -1},
    };

    public static float[] getNeighborPenalties() {
        float[] penalties = new float[NEIGHBOR_COUNT];
        for (int i = 0; i < FACE_COUNT; i++)            penalties[i]              = 1.0f;
        for (int i = FACE_COUNT; i < FACE_COUNT + EDGE_COUNT; i++) penalties[i]   = EDGE_P;
        for (int i = FACE_COUNT + EDGE_COUNT; i < NEIGHBOR_COUNT; i++) penalties[i] = CORNER_P;
        return penalties;
    }

    public static void writeGlslHeader(Path out) throws IOException {
        loadCalibration();
        String content =
            "// AUTO-GENERATED by :api:generateStencilGlsl — DO NOT EDIT MANUALLY.\n" +
            "// Source of truth: PFSFStencil.java (Aligned with Shinozaki-Oono Isotropic Model)\n" +
            "#ifndef STENCIL_CONSTANTS_GLSL\n" +
            "#define STENCIL_CONSTANTS_GLSL\n" +
            "\n" +
            "#define EDGE_P   " + EDGE_P + "\n" +
            "#define CORNER_P " + CORNER_P + "\n" +
            "\n" +
            "#endif\n";
        Files.createDirectories(out.getParent());
        Files.writeString(out, content, StandardCharsets.UTF_8);
    }

    public static void main(String[] args) throws IOException {
        if (args.length > 0) {
            writeGlslHeader(Paths.get(args[0]));
        }
    }
}
