// AUTO-GENERATED by :api:generateStencilGlsl — DO NOT EDIT MANUALLY.
// Source of truth: PFSFStencil.java (synced with pfsf_calibration.json)
// v0.4d: Shinozaki-Oono Isotropic Laplacian 26-connectivity weights
// EDGE_P   = 0.5       (√2 neighbour, Shinozaki-Oono standard)
// CORNER_P = 0.1666667 (√3 neighbour, 1/6, Shinozaki-Oono standard)
#ifndef STENCIL_CONSTANTS_GLSL
#define STENCIL_CONSTANTS_GLSL

#define EDGE_P   0.5
#define CORNER_P 0.1666667

#endif
