// AUTO-GENERATED by :api:generateStencilGlsl — DO NOT EDIT MANUALLY.
// Source of truth: PFSFStencil.java
// To regenerate: ./gradlew :api:generateStencilGlsl
#ifndef STENCIL_CONSTANTS_GLSL
#define STENCIL_CONSTANTS_GLSL

// 邊鄰居（12 個）剪力懲罰係數 — PFSFStencil.EDGE_P
#define EDGE_P   0.35

// 角鄰居（8 個）剪力懲罰係數 — PFSFStencil.CORNER_P
#define CORNER_P 0.15

#endif // STENCIL_CONSTANTS_GLSL
